name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v4
      -   name: Install Rust toolchain
          uses: dtolnay/rust-toolchain@v1
          with:
            toolchain: stable
      -   run: |
            cargo test --all-features --tests

  docs:
    name: Docs
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      -   uses: actions/checkout@v4
      -   name: Install Rust toolchain
          uses: dtolnay/rust-toolchain@v1
          with:
            toolchain: stable
      -   run: |
            cargo doc --all-features --no-deps
            cargo test --all-features --doc

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v4
      -   name: Install Rust toolchain
          uses: dtolnay/rust-toolchain@v1
          with:
            toolchain: stable
            components: clippy
      -   run: |
            cargo clippy --all-features -- -Dwarnings

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v4
      -   name: Install Rust toolchain
          uses: dtolnay/rust-toolchain@v1
          with:
            toolchain: stable
            components: rustfmt
      -   run: |
            cargo fmt -- --check
